// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: proto/product.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProductAnalyzer_AnalyzeProduct_FullMethodName = "/proto.ProductAnalyzer/AnalyzeProduct"
	ProductAnalyzer_UpdateProduct_FullMethodName  = "/proto.ProductAnalyzer/UpdateProduct"
)

// ProductAnalyzerClient is the client API for ProductAnalyzer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductAnalyzerClient interface {
	AnalyzeProduct(ctx context.Context, in *ProductData, opts ...grpc.CallOption) (*AnalysisResult, error)
	UpdateProduct(ctx context.Context, in *ProductUpdateRequest, opts ...grpc.CallOption) (*ProductUpdateResponse, error)
}

type productAnalyzerClient struct {
	cc grpc.ClientConnInterface
}

func NewProductAnalyzerClient(cc grpc.ClientConnInterface) ProductAnalyzerClient {
	return &productAnalyzerClient{cc}
}

func (c *productAnalyzerClient) AnalyzeProduct(ctx context.Context, in *ProductData, opts ...grpc.CallOption) (*AnalysisResult, error) {
	out := new(AnalysisResult)
	err := c.cc.Invoke(ctx, ProductAnalyzer_AnalyzeProduct_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productAnalyzerClient) UpdateProduct(ctx context.Context, in *ProductUpdateRequest, opts ...grpc.CallOption) (*ProductUpdateResponse, error) {
	out := new(ProductUpdateResponse)
	err := c.cc.Invoke(ctx, ProductAnalyzer_UpdateProduct_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductAnalyzerServer is the server API for ProductAnalyzer service.
// All implementations must embed UnimplementedProductAnalyzerServer
// for forward compatibility
type ProductAnalyzerServer interface {
	AnalyzeProduct(context.Context, *ProductData) (*AnalysisResult, error)
	UpdateProduct(context.Context, *ProductUpdateRequest) (*ProductUpdateResponse, error)
	mustEmbedUnimplementedProductAnalyzerServer()
}

// UnimplementedProductAnalyzerServer must be embedded to have forward compatible implementations.
type UnimplementedProductAnalyzerServer struct {
}

func (UnimplementedProductAnalyzerServer) AnalyzeProduct(context.Context, *ProductData) (*AnalysisResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeProduct not implemented")
}
func (UnimplementedProductAnalyzerServer) UpdateProduct(context.Context, *ProductUpdateRequest) (*ProductUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedProductAnalyzerServer) mustEmbedUnimplementedProductAnalyzerServer() {}

// UnsafeProductAnalyzerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductAnalyzerServer will
// result in compilation errors.
type UnsafeProductAnalyzerServer interface {
	mustEmbedUnimplementedProductAnalyzerServer()
}

func RegisterProductAnalyzerServer(s grpc.ServiceRegistrar, srv ProductAnalyzerServer) {
	s.RegisterService(&ProductAnalyzer_ServiceDesc, srv)
}

func _ProductAnalyzer_AnalyzeProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAnalyzerServer).AnalyzeProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAnalyzer_AnalyzeProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAnalyzerServer).AnalyzeProduct(ctx, req.(*ProductData))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductAnalyzer_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAnalyzerServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAnalyzer_UpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAnalyzerServer).UpdateProduct(ctx, req.(*ProductUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductAnalyzer_ServiceDesc is the grpc.ServiceDesc for ProductAnalyzer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductAnalyzer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProductAnalyzer",
	HandlerType: (*ProductAnalyzerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeProduct",
			Handler:    _ProductAnalyzer_AnalyzeProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ProductAnalyzer_UpdateProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/product.proto",
}
